### PR TITLE
Added new properties and custom code for *me()*

### PR DESCRIPTION
**Pull request by marchrius**

### CODE REVIEW

**Comment by marchrius** [comment]
Changed mapUserToObject to public

**Comment by mayoz** [comment]
@Marchrius sorry for late answer. Why did you change mapUserToObject visibility to public?

**Comment by marchrius** [comment]
Hi @mayoz, in a login / register workflow I can get user public info starting using a code or an accessToken. In first case the library do all the needed tasks
1. Get code
2. Call REST service for access_token
3. Set access_token
4. Get user data
5. Map user to object `User`

In other way, if the process start from access_token I cannot use the `Instagram::me()` due a full process. So I had to call the `getUser()` method and then mapUserToObject externally.

Obviously could be done in a different way, passing an `access_token` instead of `code` to `Instagram:me()` method.

**Comment by mayoz** [comment]
Obviously, the auth process has to do all the tasks you write. Even if you know access_token you need to verify.

I think, fork and customize it according to your app needs.

**Pull request closed without merging**
